#! /bin/sh

# Set a lower refresh rate for bspwm
bspc config -m focused refresh_rate 30

pgrep -x sxhkd > /dev/null || sxhkd &

#Just need 5
bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config presel_feedback_color '#CB6FA1'
bspc config focused_border_color '#CB6FA1'
bspc config active_border_color '#CB6FA1'

#AutoStart applications

# CORE PACKAGES
sxhkd & 
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &i

# POLYBAR And NetworkManager appleti
$HOME/.config/polybar/launch.sh --shades &
nm-applet &i

# EXTRA
bspc rule -a FloatingKitty state=floating rectangle=1000x520+450+300 &
kitty --class FloatingKitty --config ~/.config/kitty/float_window_ff.conf --hold fastfetch &
/home/andre/autostart/keyboard_rgb.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1i &

# SCREEN TIMEOUT AND XSET CONFIGS 
xss-lock -- betterlockscreen -l &
xset dpms 300 300 300
